### ISSUE TITLE
pyyaml not on the binder

### ISSUE THREAD

**Issue by michaelwexler** [stefmolin/pandas-workshop#5]
Your binder config probably needs to state dependency on pyyaml so the environment checker will work.

**Comment by stefmolin** [comment]
Hi there - I'm in the process of updating everything, so you must have caught it in the middle. The issue was that the Binder configuration is using `ruamel`, while the GitHub Actions Linux runner is using `pyyaml`. No need to add a dependency.

**Comment by michaelwexler** [comment]
Probably so.  I'll refresh and try again, plus I now know about ruamel.
