### ISSUE TITLE
Minor: median() is not average

### ISSUE THREAD

**Issue by michaelwexler** [stefmolin/pandas-workshop#6]
In "getting started" notebook and slides, you mention: What was the mass of the average meterorite? and then use the median.  Totally fair, but perhaps worth showing mean() then pointing out that median() accounts for outliers giving a better indication of "centrality".  Or don't worry about it, minor point.

**Comment by stefmolin** [comment]
This repo is a workshop that I present and that is always something I mention (as I'm sure you noticed, the rest of the slide deals with quantiles at the extremes of the distribution as a follow-up). Obviously, the slides can't have everything I say or it would be a book :smile:

**Comment by michaelwexler** [comment]
True, but this is such a nice tutorial that it can stand on it's own, so a note in the slides/notebook wouldn't hurt.  Still, like I said, minor point.
